opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_count
  - empty_string
# - empty_xctest_method
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
# - function_default_parameter_at_end
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
# - modifier_order
  - multiline_arguments
  - multiline_parameters
  - number_separator
  - operator_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - required_enum_case
  - sorted_first_last
  - sorted_imports
  - trailing_closure
# - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

disabled_rules:
  - large_tuple
