# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.3
language: objective-c
cache:
  - bundler
  - cocoapods
podfile: Example/Podfile
before_install:
  - bundle install
  - bundle exec pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SwiftConfig.xcworkspace -scheme SwiftConfig-Example | xcpretty
  - bundle exec pod lib lint
